# Generated by Django 6.0.6 on 2026-07-03 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Marka Adı')),
                ('iletisim_kisi', models.CharField(max_length=100, verbose_name='İletişim Kurulacak Kişi')),
                ('eposta', models.EmailField(max_length=254, unique=True, verbose_name='E-Posta Adresi')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif Müşteri mi?')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uretici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('instagram_kullanici_adi', models.CharField(blank=True, max_length=50, null=True)),
                ('tiktok_kullanici_adi', models.CharField(blank=True, max_length=50, null=True)),
                ('portfolyo_linki', models.URLField(blank=True, null=True, verbose_name='Portfolyo / Medya Kiti')),
            ],
        ),
        migrations.CreateModel(
            name='Proje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=150, verbose_name='Proje Başlığı')),
                ('teslim_tarihi', models.DateField(verbose_name='Son Teslim Tarihi')),
                ('butce', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bütçe (TL)')),
                ('tamamlandi_mi', models.BooleanField(default=False)),
                ('marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projeler', to='kullanici.marka')),
                ('uretici', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projeler', to='kullanici.uretici')),
            ],
        ),
    ]
